FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src/frontend

# Copy the .csproj file and restore dependencies
COPY ./frontend/BlazorGrpcClient/*.csproj ./BlazorGrpcClient/
RUN dotnet restore BlazorGrpcClient/BlazorGrpcClient.csproj

# Copy everything else and build the app
COPY ./frontend/BlazorGrpcClient/. ./BlazorGrpcClient/
COPY ./proto/. /src/proto/
# WORKDIR /src/frontend/BlazorGrpcClient
RUN dotnet build BlazorGrpcClient/BlazorGrpcClient.csproj -c Release -o /app/build
CMD ["tail", "-f", "/dev/null"]
# # Publish the app
# FROM build AS publish
# RUN dotnet publish BlazorGrpcClient/BlazorGrpcClient.csproj -c Release -o /app/publish

# # Final stage/image
# FROM nginx:alpine AS final
# WORKDIR /usr/share/nginx/html
# COPY --from=publish /app/publish/wwwroot .
# COPY ./frontend/nginx.conf /etc/nginx/nginx.conf
# EXPOSE 80